baseurl = "https://arnocat.github.io"
languageCode = "zh"
defaultContentLanguage = "zh"
enableRobotsTXT = true
hasCJKLanguage = true
title = "Arno"
theme = "dream"

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
lightTheme = "emerald"
darkTheme = "forest"

backgroundImage = "/background.jpg"
backgroundImageDark = ""

author = "Arno"
description = "Arno 的生活记录~"
avatar = "/img/avatar.png"
headerTitle = "arno cat home"
motto = "与其感慨路难行，不如马上出发"

# footerBottomText = ""

rss = true

utterancesRepo = "arnocat/arnocat.github.io"

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
# VALINE_LANGUAGE = ""

email = "q243284589@gmail.com"

siteStartYear = 2016

favicon = "/img/favicon.ico"

# Syntax highlighting
customSyntaxHighlighting = true
[markup]
[markup.highlight]
noClasses = false

# options
stickyNav = true
showSummaryCoverInPost = true
# hasTwitterEmbed = true

[params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"
